services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: wkesselr
      POSTGRES_PASSWORD: Securitas2025!
      POSTGRES_DB: wkesselr_db1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: